#!/usr/bin/env bash
#ddev-generated
## Description: Run command line utility for Backdrop CMS
## Usage: bee
## Example: ddev bee

ddev exec /usr/local/bin/bee/bee.php --root='/var/www/html/$DDEV_DOCROOT' --uri='$DDEV_PRIMARY_URL' $@
exit_code=$?

# Sync between host and container
if ! ddev mutagen sync >/dev/null 2>&1; then
    echo "Mutagen sync failed"
    exit 1
fi

exit $exit_code
